### PR TITLE
Fix Ant target for SDK drop in use.

### PR DESCRIPTION
**Pull request by niedzielski**
- Update the Ant target in the build instructions so the build output can be used as an SDK drop in.
- Provided an example of replacing the default SDK jar with Facebook jar.

### CODE REVIEW

**Comment by niedzielski** [comment]
All signed up with no place to go. https://youtu.be/5YBcy3U7uw8?t=3m33s

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by alsutton** [comment]
We've rebased on a more recent version which has changed the location of the build files. Can you update your patch for the new location. Thanks.

**Comment by alsutton** [comment]
Closing the pull request because it is out of date with the file locations since the rebase.

**Pull request closed without merging**
