### PR TITLE
Workaround for #620

### PR DESCRIPTION
**Pull request by Thog**
Related to https://sourceforge.net/p/proguard/bugs/620/

### CODE REVIEW

**Comment by alsutton** [comment]
Have you got some test cases to show this working?

**Comment by Thog** [comment]
Basically, If you use the obfuscator and a FunctionalInterface on your project, the function name of the interface will not be renamed in the BootstrapMethods attribute. A simple test case can be found on the SourceForge issue https://sourceforge.net/p/proguard/bugs/620/#55ca

**Comment by alsutton** [comment]
I'm wondering if this fix should go upstream into the main proguard codebase. I'd like to ensure we stick as closely to the upstream codebase to allow us to upgrade easily, and if this is a bug in the upstream code it would be better to fix it there.

**Comment by alsutton** [comment]
I'm going to close this out without merging because my view is this should go upstream to the Proguard SourceForge repository. I'd like to avoid us diverging from their code base, and the bug is a bug in the upstream code, so please submit your patch to them so everyone using proguard can benefit.

**Comment by Thog** [comment]
Actually, I already have send my fix to the original proguard but I haven't get any response from them https://sourceforge.net/p/proguard/code/merge-requests/4/

**Pull request closed without merging**
